jdk:
  - openjdk17

before_install:
  - yes | sdkmanager --licenses

git:
  submodules: true

install:
  - chmod +x ./jitpack.sh
  - ./jitpack.sh

artifacts:
  - path: ffmpeg-kit/android/ffmpeg-kit-android-lib/build/outputs/aar/ffmpeg-kit-release.aar
    type: aar
